export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTERS_NUMBER = "FETCH_CHARACTERS_NUMBER";
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const FETCH_EPISODES = "FETCH_EPISODES";
export const LOADING = "LOADING";
